import csv

SRC = 'design/spec/minimax_audio_prompts.csv'

# Read existing valid rows
with open(SRC, 'r', encoding='utf-8') as f:
    rows = list(csv.reader(f))

header = rows[0]
# Keep only the original complete rows (everything up to and including A5, the last original).
clean = [header]
for r in rows[1:]:
    if len(r) != 9 or r[0] == '':
        # truncated/corrupt row from the failed heredoc append — stop here
        break
    clean.append(r)
    if r[0] == 'A5':
        break

print(f'Kept {len(clean)-1} clean original rows (header + through A5)')

supp = [
    ['S14','SFX','Sfx/Scenario/signal_gate','P0',1.2,'no','wav','-9','A scenario-mechanic activation sound effect for the Signal Gate command (holds enemy deployment) in a tower-defense game, industrial aesthetic. A heavy industrial relay clunk, a descending steam-seal hiss, and a low-frequency containment hum onset. The feeling of a bulkhead slamming shut to hold the enemy back. 1.2s, mono, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO force-field hum, NO sci-fi shield.'],
    ['S15','SFX','Sfx/Scenario/reinforcement_train','P0',2,'no','wav','-9','A scenario-mechanic activation sound effect for the Reserve Train command (timed reinforcement) in a tower-defense game, industrial aesthetic. A distant train horn approaching with Doppler, growing rail-clatter, then a heavy arrival brake-squeal and steam release. The feeling of relief forces arriving. 2s, mono, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO modern train horn, NO cartoonish choo-choo.'],
    ['S16','SFX','Sfx/Scenario/route_switch','P0',1.5,'no','wav','-9','A scenario-mechanic activation sound effect for the Route Switch command (cycles enemy traffic center/left/right) in a tower-defense game, industrial aesthetic. A heavy mechanical switch-throw ka-CHUNK, a rail-translation rumble moving across the stereo field, a secondary clunk as the new route locks. 1.5s, stereo, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO transformer sound, NO sci-fi teleport.'],
    ['S17','SFX','Sfx/Scenario/kiln_purge','P0',1.8,'no','wav','-9','A scenario-mechanic activation sound effect for the Kiln Purge command (environment-device AoE purge) in a tower-defense game, industrial aesthetic. A deep furnace-draw roar building for 1 second, then a percussive heat-blast release with ash and cinder debris. 1.8s, mono, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO explosion, NO generic fireball.'],
    ['S18','SFX','Sfx/Scenario/boss_breaker','P0',1.5,'no','wav','-9','A scenario-mechanic activation sound effect for the Boss Breaker command (suppresses a boss surge phase) in a tower-defense game, industrial aesthetic. Three overlapping mechanical clunks in quick succession, a heavy electromagnetic thump, a descending metal-stress groan as the boss is forced back. 1.5s, mono, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO laser blast, NO sci-fi EMP.'],
    ['S19','SFX','Sfx/Resonance/window_close','P0',0.6,'no','wav','-12','A resonance-window expiration sound effect for a tower-defense game, industrial aesthetic with one allowed transcendent flavor. A warm descending shimmer as the ember opportunity fades, the metallic overtone ringing down to silence, a soft ash-sizzle tail. The feeling of a window closing, melancholic not punitive. 600ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO error buzzer, NO power-down bleep.'],
    ['S20','SFX','Sfx/Resonance/matrix_convergence','P0',2,'no','wav','-6','A matrix-convergence trigger sound effect, the rare climax of the resonance system (requires 6 specialization matches) in a tower-defense game, industrial dark ambient with transcendent flavor. The most powerful cue in the game, must feel earned. Six overlapping metallic tones converging into a single harmonic unity, a rising warm-noise swell, a female wordless hum at the peak, then a bright metallic release. 2s, stereo, -6 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO generic power-up, NO EDM build-up drop.'],
    ['S21','SFX','Sfx/Status/specialization_ult','P0',0.9,'no','wav','-9','A tower-specialization ultimate-trigger sound effect for a tower-defense game, industrial aesthetic. A bright ascending metallic harmonic sweep capped by a single pure resonant chime, with a faint mechanical overdrive underneath. A weapon reaching its final form. 900ms, mono, -9 LUFS, critical layer. Must evoke the last railway of a dying ember civilization. NO RPG level-up stinger, NO magic sparkle.'],
    ['E1','SFX','Sfx/Enemy/burrow_ambush','P1',0.6,'no','wav','-12','An enemy special-mechanic sound effect for the Burrow Sapper mid-route ambush burst (at 55 percent route progress) in a tower-defense game, industrial aesthetic. An underground churning rumble building for 400ms, then a wet percussive crack as the creature surfaces, plus loose-dirt scatter. An ambush being sprung. 600ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO cartoonish pop-up, NO monster roar.'],
    ['E2','SFX','Sfx/Enemy/spore_split','P1',0.8,'no','wav','-12','An enemy special-mechanic sound effect for the Spore Carrier splitting into smaller Ash Swarms on death in a tower-defense game, industrial aesthetic. A wet membrane pop followed by a flurry of small chitinous dispersal ticks spreading outward, with a faint ash-hiss. 800ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO alien birth, NO cartoonish splat.'],
    ['E3','SFX','Sfx/Enemy/mimic_shift','P1',0.7,'no','wav','-12','An enemy special-mechanic sound effect for the Echo Mimic copying a threat form at spawn in a tower-defense game, industrial aesthetic. An unstable pitch-gliding metallic wobble that cannot settle, like a shape trying to lock, capped by a brief crystalline snap when it resolves. 700ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO sci-fi morph, NO transformer sound.'],
    ['E4','SFX','Sfx/Enemy/attrition_siphon','P1',0.5,'no','wav','-15','An enemy special-mechanic sound effect for the Ember Leech periodic attrition siphon (drains resources) in a tower-defense game, industrial aesthetic. A low pulsing vacuum draw like a slow inhale through a metal pipe, with a faint ember-crackle. Unsettling and parasitic. 500ms, mono, -15 LUFS. Must evoke the last railway of a dying ember civilization. NO vampire drain, NO sci-fi tractor beam.'],
    ['E5','SFX','Sfx/Enemy/support_link','P1',0.4,'no','wav','-15','An enemy special-mechanic sound effect for the Rail Warden support link (shielding aura onto nearby armored/heavy/boss enemies) in a tower-defense game, industrial aesthetic. A brief resonant coupling tone, two metallic notes locking into harmony, with a faint sustained hum. A defensive link engaging. 400ms, mono, -15 LUFS. Must evoke the last railway of a dying ember civilization. NO sci-fi shield hum, NO magic aura.'],
    ['E6','SFX','Sfx/Enemy/elite_pressure','P1',0.5,'no','wav','-15','An enemy special-mechanic sound effect for elite enemies (husk_titan) entering a pressure state below 55 percent HP in a tower-defense game, industrial aesthetic. A low menacing mechanical groan building in intensity like a great engine pushed past its limit, with a stress-metal creak. Threatening and relentless. 500ms, mono, -15 LUFS. Must evoke the last railway of a dying ember civilization. NO monster rage, NO berserk scream.'],
    ['U10','SFX','Sfx/Ui/early_dispatch','P1',0.4,'no','wav','-12','A wave-early-dispatch UI sound effect, played when the player voluntarily skips prep time to start the wave early in a tower-defense game, industrial aesthetic. A sharp steam-whistle toot plus an urgent mechanical lever-throw chunk. A decisive aggressive choice trading safety for tempo. 400ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO alarm buzzer, NO cartoonish toot.'],
    ['U11','SFX','Sfx/Ui/level_select','P1',0.3,'no','wav','-15','A campaign-level-select UI sound effect for a tower-defense game, industrial aesthetic. A focused mechanical clack of a route lever engaging plus a faint railway-points translation rumble. Choosing a destination on the rail network. 300ms, mono, -15 LUFS. Must evoke the last railway of a dying ember civilization. NO generic UI blip, NO map ping.'],
    ['U12','SFX','Sfx/Ui/deploy_confirm','P1',0.7,'no','wav','-12','A mission-deployment-confirm UI sound effect for a tower-defense game, industrial aesthetic. A coordinated launch sequence: a deep mechanism cycling up, a heavy relay clunk, a final steam-blast release. Committing to a mission and the line going live. 700ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO rocket launch, NO generic confirm.'],
    ['U13','SFX','Sfx/Ui/chapter_reward','P1',0.8,'no','wav','-12','A chapter-reward-claim UI sound effect for a tower-defense game, industrial aesthetic. A warm metallic chord of three ascending bell tones with a subtle reverberant tail. A permanent upgrade being installed. Earned and durable, not flashy. 800ms, mono, -12 LUFS. Must evoke the last railway of a dying ember civilization. NO RPG fanfare, NO coin collect.'],
    ['U14','SFX','Sfx/Ui/tutorial_complete','P2',0.5,'no','wav','-15','A tutorial-completion UI sound effect for a tower-defense game, industrial aesthetic. A brief gentle resolve: a single warm metallic bell tone with a soft decay, plus a faint mechanical sigh of release. The player is ready. 500ms, mono, -15 LUFS. Must evoke the last railway of a dying ember civilization. NO cartoonish ta-da, NO generic complete chime.'],
]

all_rows = clean + supp
with open(SRC, 'w', encoding='utf-8', newline='') as f:
    csv.writer(f).writerows(all_rows)

print(f'Wrote {len(all_rows)-1} total rows = {len(clean)-1} original + {len(supp)} supplement')
