"""
Emberline Defense SFX post-processor.

Reads the raw SFX generated by batch_text_to_music (typically 30-200s of
ambient/atmosphere output) and produces a game-ready SFX trimmed to the
target duration from `design/spec/minimax_prompt_full.txt`, converted to
mono or stereo per spec, with a 5 ms fade in/out, and normalized to the
target integrated loudness in LUFS.

Usage:
    python post_process_sfx.py [--dry-run]

Inputs:
    output/audio/sfx/**/*.wav     (raw, long)

Outputs:
    output/audio/sfx_final/**/*.wav
"""

import argparse
import sys
import wave
import struct
from pathlib import Path
import numpy as np
import pyloudnorm as pyln

SR = 44100
FADE_S = 0.005  # 5 ms fade in/out per spec
SILENCE_THRESH = 0.02  # peak amplitude considered "silence"
PEAK_CEIL_DBFS = -3.0  # spec: 峰值 ≤ -3 dBTP (dBFS sample peak ceiling)

# (duration_sec, target_lufs, mono)
# Source: design/spec/minimax_prompt_full.txt section 5 (P0/P1/P2 SFX)
SPEC = {
    # P0 tower fire
    "fire_rail_lancer":      (0.40, -12, True),
    "fire_cinder_mortar":    (0.35, -12, True),
    "fire_arc_welder":       (0.50, -12, True),
    "fire_siege_drill":      (0.70, -12, True),
    # P0 combat events
    "death_generic":         (0.25, -15, True),
    "enemy_leak":            (0.40,  -9, True),
    "boss_spawn":            (3.00,  -6, True),
    "boss_phase_shift":      (1.20,  -6, True),
    # P0 resonance
    "window_open":           (1.00,  -9, True),
    "ember_surge":           (0.80,  -9, False),  # stereo
    "fracture_mark":         (0.80,  -9, False),  # stereo
    # P0 UI
    "tower_place":           (0.50, -12, True),
    "tower_upgrade":         (0.40, -12, True),
    "wave_start":            (1.50, -12, True),
    "routine_hit":           (0.10, -18, True),
    "boss_hit":              (0.30,  -9, True),
    # P1 tower fire
    "fire_frost_coil":       (0.60, -15, True),
    "fire_ember_flak":       (0.30, -12, True),
    "fire_resonance_beacon": (0.80, -15, True),
    "fire_grav_snare":       (0.60, -12, True),
    # P1 sfx
    "critical_hit":          (0.18, -12, True),
    "armor_break":           (0.25, -15, True),
    "slow_apply":            (0.22, -18, True),
    "wave_clear":            (1.20, -12, True),
    "click_confirm":         (0.10, -15, True),
    # P2 ui micro
    "hover":                 (0.06, -24, True),
    "panel_open":            (0.25, -18, True),
    "panel_close":           (0.20, -18, True),
    "tutorial_advance":      (0.20, -18, True),
    "expose_mark":           (0.45, -18, True),
    # === second P0 batch (8 critical scene/resonance/specialization cues) ===
    "signal_gate":          (1.20,  -9, True),
    "reinforcement_train":  (2.00,  -9, True),
    "route_switch":         (1.50,  -9, False),  # stereo
    "kiln_purge":           (1.80,  -9, True),
    "boss_breaker":         (1.50,  -9, True),
    "window_close":         (0.60, -12, True),
    "matrix_convergence":   (2.00,  -6, False),  # stereo
    "specialization_ult":   (0.90,  -9, True),
    # === third batch: 11 P1/P2 (6 enemy + 4 campaign UI + 1 tutorial) ===
    "burrow_ambush":        (0.60, -12, True),
    "spore_split":          (0.80, -12, True),
    "mimic_shift":          (0.70, -12, True),
    "attrition_siphon":     (0.50, -15, True),
    "support_link":         (0.40, -15, True),
    "elite_pressure":       (0.50, -15, True),
    "level_select":         (0.30, -15, True),
    "deploy_confirm":       (0.70, -12, True),
    "chapter_reward":       (0.80, -12, True),
    "early_dispatch":       (0.40, -12, True),
    "tutorial_complete":    (0.50, -15, True),
}


def read_wav(path: Path):
    """Read any PCM WAV into float64 numpy in [-1, 1], shape (n,) or (n, ch)."""
    with wave.open(str(path), "rb") as wf:
        sr = wf.getframerate()
        n_ch = wf.getnchannels()
        sw = wf.getsampwidth()
        n = wf.getnframes()
        raw = wf.readframes(n)
    if sw == 2:
        samples = np.frombuffer(raw, dtype="<i2").astype(np.float64) / 32768.0
    elif sw == 3:
        b = np.frombuffer(raw, dtype=np.uint8).reshape(-1, 3)
        i = (b[:, 0].astype(np.int32)
             | (b[:, 1].astype(np.int32) << 8)
             | (b[:, 2].astype(np.int32) << 16))
        # sign extend
        i = (i ^ 0x800000) - 0x800000
        samples = i.astype(np.float64) / 8388608.0
    elif sw == 4:
        samples = np.frombuffer(raw, dtype="<i4").astype(np.float64) / 2147483648.0
    else:
        raise ValueError(f"unsupported sample width {sw}")
    if n_ch > 1:
        samples = samples.reshape(-1, n_ch)
    return samples, sr, n_ch


def write_wav(path: Path, samples: np.ndarray, sr: int):
    """Write float64 [-1, 1] numpy to 16-bit PCM WAV."""
    if samples.ndim == 1:
        samples = samples.reshape(-1, 1)
    # peak limiter at PEAK_CEIL_DBFS
    peak = float(np.max(np.abs(samples))) if samples.size else 0.0
    if peak > 0:
        target = 10 ** (PEAK_CEIL_DBFS / 20)
        if peak > target:
            samples = samples * (target / peak)
    # clip
    samples = np.clip(samples, -1.0, 1.0)
    i16 = (samples * 32767.0).astype("<i2")
    n_ch = i16.shape[1]
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(n_ch)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        wf.writeframes(i16.tobytes())


def find_sound_start(samples: np.ndarray, sr: int) -> int:
    """Index of first sample where peak amplitude exceeds silence threshold."""
    if samples.ndim == 1:
        peak = np.abs(samples)
    else:
        peak = np.max(np.abs(samples), axis=1)
    above = np.where(peak > SILENCE_THRESH)[0]
    return int(above[0]) if len(above) else 0


def find_loudest_window(samples: np.ndarray, target_n: int) -> int:
    """Start index of the target_n-sample window with the highest RMS energy.

    This preserves the 'attack' / peak moment of the source, which is what a
    game SFX actually needs (rather than the first non-silent moment, which
    can land in a quiet intro).
    """
    if samples.ndim == 1:
        peak = np.abs(samples)
    else:
        peak = np.max(np.abs(samples), axis=1)
    if peak.shape[0] <= target_n:
        return 0
    sq = peak ** 2
    cs = np.concatenate([[0.0], np.cumsum(sq)])
    # window sum for window starting at i = cs[i+target_n] - cs[i]
    window_sums = cs[target_n:] - cs[: cs.shape[0] - target_n]
    return int(np.argmax(window_sums))


def measure_lufs(samples: np.ndarray, sr: int) -> float:
    """Integrated LUFS, returns -inf if too short / silent for measurement."""
    if samples.ndim == 1:
        s = samples.reshape(-1, 1)
    else:
        s = samples
    if np.max(np.abs(s)) < 1e-6 or s.shape[0] < int(0.4 * sr):
        return float("-inf")
    meter = pyln.Meter(sr)
    try:
        return float(meter.integrated_loudness(s))
    except Exception:
        return float("-inf")


def normalize_lufs(samples: np.ndarray, sr: int, target_lufs: float,
                   peak_ceil_dbfs: float = PEAK_CEIL_DBFS) -> np.ndarray:
    """Strict LUFS-target with peak ceiling via hard clip.

    1) measure integrated LUFS, compute gain to hit target
    2) apply gain
    3) hard-clip at peak_ceil_dbfs (game-SFX convention; mild distortion
       is acceptable and the alternative is to leave the file 10+ dB too
       quiet, which makes it useless in a busy mix)

    For clips < 0.4s (LUFS unmeasurable), fall back to peak normalization
    at the ceiling.
    """
    measured = measure_lufs(samples, sr)
    if measured == float("-inf"):
        return peak_normalize(samples, peak_ceil_dbfs)
    desired_gain_db = target_lufs - measured
    boosted = samples * (10 ** (desired_gain_db / 20))
    threshold = 10 ** (peak_ceil_dbfs / 20)
    return np.clip(boosted, -threshold, threshold)


def peak_normalize(samples: np.ndarray, target_dbfs: float) -> np.ndarray:
    peak = float(np.max(np.abs(samples))) if samples.size else 0.0
    if peak <= 0:
        return samples
    target = 10 ** (target_dbfs / 20)
    return samples * (target / peak)


def to_mono(samples: np.ndarray) -> np.ndarray:
    if samples.ndim == 1:
        return samples
    return samples.mean(axis=1)


def apply_fade(samples: np.ndarray, sr: int, fade_s: float = FADE_S) -> np.ndarray:
    """Apply 5 ms fade-in at start and 5 ms fade-out at end."""
    n = samples.shape[0]
    fade = max(1, int(fade_s * sr))
    fade = min(fade, n // 2)
    if fade <= 0:
        return samples
    env = np.ones(n, dtype=np.float64)
    env[:fade] = np.linspace(0.0, 1.0, fade)
    env[-fade:] = np.linspace(1.0, 0.0, fade)
    if samples.ndim == 1:
        return samples * env
    return samples * env[:, None]


def process_one(in_path: Path, out_path: Path, duration: float,
                lufs: float, mono: bool, dry_run: bool = False):
    samples, sr, n_ch = read_wav(in_path)
    # resample not needed (we requested 44100 from generator)
    if sr != SR:
        # minimal: just trim using original SR; write_wav will preserve
        pass

    # find the loudest target-duration window in the source, so the
    # output SFX preserves the attack/peak moment rather than a quiet intro
    target_n = int(duration * sr)
    start = find_loudest_window(samples, target_n)
    samples = samples[start:start + target_n]

    # trim/pad to target duration
    target_n = int(duration * sr)
    if samples.shape[0] >= target_n:
        samples = samples[:target_n]
    else:
        pad = np.zeros((target_n - samples.shape[0],) if samples.ndim == 1
                       else (target_n - samples.shape[0], samples.shape[1]))
        samples = np.concatenate([samples, pad], axis=0)

    # mono / stereo
    if mono:
        samples = to_mono(samples)
    elif samples.ndim == 1:
        # duplicate to stereo so output is true stereo
        samples = np.stack([samples, samples], axis=1)

    # fade in/out
    samples = apply_fade(samples, sr)

    # normalize
    samples = normalize_lufs(samples, sr, lufs)

    if not dry_run:
        write_wav(out_path, samples, sr)
    return samples.shape[0] / sr, sr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--input", default="E:/TD/output/audio/sfx")
    ap.add_argument("--output", default="E:/TD/output/audio/sfx_final")
    args = ap.parse_args()

    in_root = Path(args.input)
    out_root = Path(args.output)

    files = sorted(in_root.rglob("*.wav"))
    if not files:
        print(f"no wav files under {in_root}", file=sys.stderr)
        return 1

    print(f"processing {len(files)} SFX -> {out_root}")
    ok = 0
    skipped = 0
    failed = 0
    for f in files:
        name = f.stem
        if name not in SPEC:
            print(f"  SKIP {name} (no spec)")
            skipped += 1
            continue
        dur, lufs, mono = SPEC[name]
        rel = f.relative_to(in_root)
        out = out_root / rel
        try:
            actual_dur, sr = process_one(f, out, dur, lufs, mono,
                                          dry_run=args.dry_run)
            ch = "mono" if mono else "stereo"
            tag = "(dry)" if args.dry_run else ""
            print(f"  OK  {name:<22} -> {rel}  {actual_dur:.3f}s / {dur}s  "
                  f"target {lufs} LUFS  {ch}  {tag}")
            ok += 1
        except Exception as e:
            print(f"  FAIL {name}: {e}")
            failed += 1

    print(f"\nsummary: ok={ok} skipped={skipped} failed={failed}")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
